#!/usr/bin/env node

var assert = require('assert'),
    color = require('cli-color'),
    config = require('./config'),
    KickStarter = require('./kickstarter'),
    DB = require('./db'),
    Map = require('./map');

var ks = new KickStarter(),
    db = new DB(),
    map = new Map();

console.log(color.reset);
console.log(color.white.bold.underline('Starting KickScraper'));

ks.login()
  .then(function() {
    return ks.get_backers();
  })
  .then(function(backers) {
    assert.notEqual(0, backers.length, 'No backers found');
    return backers;
  })
  .then(function(backers) {
    db.process_backers(backers);
  })
  .then(function() {
    map.generate();
  })
  .fail(function(error) {
    ks.emit('error', error);
  });


db.on('added_backer', function(backer) {
  ks.emit('test_message', backer);
});

ks.on('error', function(error) {
  console.log(color.red.bold('Scraper Error: ') + color.red(error));
});

map.on('error', function(error) {
  console.log(color.red.bold('Map Error: ') + color.red(error));
});

if(config.debug) {

  ks.on('sent_message', function(user, message) {
    console.log(color.green.bold.underline('Sent message to: ' + user));
    console.log(color.white(message));
  });

  ks.on('logged_in', function(user, message) {
    console.log(color.green('Logged in to KickStarter'));
  });

  ks.on('get_pledge_page', function(page) {
    console.log(color.green('Retrieved pledge page: ' + page));
  });

  map.on('generated_image', function(path) {
    console.log(color.green('Generated map image: ' + path));
  });

  map.on('uploaded_image', function(server) {
    console.log(color.green('Copied map image to: ' + server));
  });

}

